# Modified travis.yml set-up for the new native R support on Travis CI

language: r

r:
  - release
  - devel

cache: packages

sudo: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always